name: Build and Push Docker Image

on:
    push:
        branches:
            - main # Modify this to your main branch name

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build Docker image
              run: docker build -t zixties60/docker_ytarchive:latest .
              working-directory: .

            - name: Push Docker image to Docker Hub
              run: docker push zixties60/docker_ytarchive:latest
